name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate  # Linux/Mac
          echo "Virtual environment created"

      - name: Install Python dependencies
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint Python with flake8
        run: |
          source .venv/bin/activate
          pip install flake8
          # Run only critical error checks that affect functionality
          flake8 src/ --select=E9,F63,F7,F82,E226,W504,E128,F541

      - name: Lint JavaScript with ESLint
        run: |
          # ESLint מותקן כdevDependency
          npm run lint

      - name: Run Python tests
        run: |
          source .venv/bin/activate
          pip install pytest
          pytest tests/ -v

      - name: Run Node.js tests (if present)
        run: |
          # בדיקה פשוטה
          if grep -q '"test"' package.json; then
            npm test
          else
            echo "No test script found - skipping"
          fi